"""``memory migrate --rename-namespace`` (5.3) — SQL-level table rename.

Operates **directly on the SQLite database file** because renaming a
namespace is purely a metadata operation: every table in our schema
is named ``{namespace}_{suffix}``, so we just iterate
``sqlite_master`` for tables matching the old prefix and emit
``ALTER TABLE old_name RENAME TO new_name`` per row.

Supports two modes:

- **rename** (default): atomically renames all tables in a single
  transaction. The source namespace ceases to exist after this.
- **copy** (``--keep-source``): copies every row to a new set of tables
  under the new namespace, leaves the source intact. Useful for
  side-by-side testing while migrating between namespaces.

D49-C: callers can do a ``--dry-run`` via :mod:`migration.preview`,
which calls :func:`plan_rename` and renders either a terminal table
or JSON. Live execution is :func:`apply_rename`.

NB: SQLite FTS5 virtual tables (``{ns}_atoms_fts``, etc.) **can** be
renamed by ``ALTER TABLE`` in modern SQLite (3.25+). The triggers that
keep them in sync are auto-recreated by the ``_init_schema`` of the
new ``Memory`` instance opened against the renamed namespace, so the
caller is encouraged to instantiate a fresh ``Memory`` after rename.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from octop_memory.storage.backends.fts_text import register_fts_functions

RenameMode = Literal["rename", "copy"]


@dataclass
class TablePlan:
    """One step in a rename plan."""

    src_table: str
    dst_table: str
    row_count: int
    """Best-effort count for diagnostics (``COUNT(*)`` on the source).
    Skipped (-1) for FTS shadow tables which can be expensive to count."""

    is_fts_shadow: bool = False
    """``True`` for FTS5 virtual tables and their internal shadow tables
    (``_data``, ``_idx``, ``_docsize``, ``_content``, ``_config``).
    Renamed via ``ALTER TABLE`` like any other table; flagged so the
    CLI can group them in the dry-run output."""


@dataclass
class RenamePlan:
    """Full rename / copy plan, generated by :func:`plan_rename`.

    ``conflicts`` lists destination table names that already exist —
    the operation is **refused** unless the caller passes
    ``allow_overwrite=True`` (which deletes the conflicting destination
    first).
    """

    db_path: Path
    src_namespace: str
    dst_namespace: str
    mode: RenameMode
    steps: list[TablePlan] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)

    @property
    def total_rows(self) -> int:
        return sum(s.row_count for s in self.steps if s.row_count >= 0)

    @property
    def has_conflicts(self) -> bool:
        return bool(self.conflicts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


# FTS5 maintains internal "shadow" tables with these suffixes; they are
# auto-managed by the parent virtual table. Renaming the virtual table
# cascades to its shadows automatically, so listing them as separate
# rename steps would actually fail (SQLite refuses to ALTER shadow
# tables directly). We filter them out from the planning phase.
_FTS_SHADOW_TAIL = ("_fts_data", "_fts_idx", "_fts_docsize", "_fts_content", "_fts_config")


def _is_fts_shadow(table: str) -> bool:
    """``True`` if ``table`` is an FTS5 internal shadow (skip during rename)."""
    return any(table.endswith(suffix) for suffix in _FTS_SHADOW_TAIL)


def _is_fts_virtual(table: str) -> bool:
    """Whether ``table`` is the FTS5 virtual table itself.

    ``True`` if ``table`` is the FTS5 virtual table itself (the one
    with a non-shadow ``_fts`` suffix). Renaming this **does** cascade
    to all shadows, so we DO include it in the plan."""
    if _is_fts_shadow(table):
        return False
    return table.endswith("_fts")


def _list_namespace_tables(conn: sqlite3.Connection, namespace: str) -> list[str]:
    """Return every user-table name beginning with ``{namespace}_``.

    We use the literal escape so a namespace containing ``_`` doesn't
    over-match (SQLite ``LIKE`` treats ``_`` as a wildcard by default).
    """
    escaped = namespace.replace("_", "\\_")
    pattern = escaped + "\\_%"
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type IN ('table')   AND name LIKE ? ESCAPE '\\' ORDER BY name",
        (pattern,),
    ).fetchall()
    return [r[0] for r in rows]


def _table_row_count(conn: sqlite3.Connection, table: str) -> int:
    """``COUNT(*)`` for ``table``, ``-1`` on error (e.g. FTS internals)."""
    try:
        cur = conn.execute(f'SELECT COUNT(*) FROM "{table}"')
        return int(cur.fetchone()[0])
    except sqlite3.Error:
        return -1


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def plan_rename(
    db_path: str | Path,
    *,
    src_namespace: str,
    dst_namespace: str,
    mode: RenameMode = "rename",
) -> RenamePlan:
    """Plan a rename without touching anything; cheap and read-only."""
    if not src_namespace:
        raise ValueError("src_namespace cannot be empty")
    if not dst_namespace:
        raise ValueError("dst_namespace cannot be empty")
    if src_namespace == dst_namespace:
        raise ValueError("src and dst namespaces are identical; nothing to do")

    path = Path(db_path).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"database file not found: {path}")

    plan = RenamePlan(db_path=path, src_namespace=src_namespace, dst_namespace=dst_namespace, mode=mode)

    # Use read-only connection so we can't accidentally mutate during planning.
    uri = f"file:{path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    try:
        all_src_tables = _list_namespace_tables(conn, src_namespace)
        # Filter out FTS shadow tables — renaming the parent FTS5 virtual
        # table cascades to its shadows automatically, and direct
        # ALTER TABLE on a shadow is rejected by SQLite.
        src_tables = [t for t in all_src_tables if not _is_fts_shadow(t)]
        if not src_tables:
            return plan

        existing_dst_tables = {t for t in _list_namespace_tables(conn, dst_namespace) if not _is_fts_shadow(t)}

        for table in src_tables:
            suffix = table[len(src_namespace) :]  # includes leading underscore
            dst_table = f"{dst_namespace}{suffix}"
            if dst_table in existing_dst_tables:
                plan.conflicts.append(dst_table)
            is_fts = _is_fts_virtual(table)
            row_count = -1 if is_fts else _table_row_count(conn, table)
            plan.steps.append(
                TablePlan(
                    src_table=table,
                    dst_table=dst_table,
                    row_count=row_count,
                    is_fts_shadow=is_fts,  # repurposed: True = FTS virtual (skip COUNT)
                )
            )
    finally:
        conn.close()

    return plan


def apply_rename(plan: RenamePlan, *, allow_overwrite: bool = False) -> int:
    """Execute the plan. Returns number of tables affected.

    Atomic: wraps the entire operation in a single SQLite transaction.
    On any error all renames roll back.

    After the rename, FTS5 virtual tables and AFTER INSERT/UPDATE/DELETE
    triggers are dropped and rebuilt from the renamed base tables.
    SQLite's ``ALTER TABLE RENAME TO`` rewrites trigger BODIES that
    reference the renamed table, but it can't fix:

    1. FTS5 ``content=...`` virtual-table parameters (which still
       point at the OLD base table name).
    2. FTS5 magic "delete" sentinel column in AFTER DELETE triggers
       (the column NAME is the FTS table itself; rename leaves it stale).

    So we drop every FTS / trigger pair under the source namespace,
    let the next ``Memory(namespace=dst)`` open re-create them via
    ``_init_schema``, then repopulate FTS via ``INSERT INTO fts(rowid,
    ...) SELECT rowid, ... FROM base``.

    Args:
        plan: result of :func:`plan_rename`. Pass directly; do not
            mutate.
        allow_overwrite: if ``True``, drops conflicting destination
            tables before renaming. Required when ``plan.has_conflicts``.
    """
    if not plan.steps:
        return 0
    if plan.has_conflicts and not allow_overwrite:
        raise ValueError(
            f"destination tables already exist: {plan.conflicts!r}; pass allow_overwrite=True to drop them first"
        )

    conn = sqlite3.connect(str(plan.db_path))
    committed = False
    try:
        # Disable autocommit; we manage the txn manually so partial
        # rename never leaves the DB half-renamed.
        conn.execute("BEGIN IMMEDIATE")

        if allow_overwrite:
            for conflict in plan.conflicts:
                conn.execute(f'DROP TABLE IF EXISTS "{conflict}"')

        if plan.mode == "rename":
            # Phase 1: drop ALL FTS virtual tables + triggers under the
            # source namespace BEFORE renaming the base tables. We'll
            # rebuild them under the destination namespace at the end.
            fts_tables = _collect_fts_tables(conn, plan.src_namespace)
            triggers = _collect_triggers(conn, plan.src_namespace)
            for trig in triggers:
                conn.execute(f'DROP TRIGGER IF EXISTS "{trig}"')
            for fts in fts_tables:
                conn.execute(f'DROP TABLE IF EXISTS "{fts}"')

            # Phase 2: rename remaining base tables. Skip the FTS tables
            # we just dropped (they're already gone).
            for step in plan.steps:
                if step.is_fts_shadow:  # marker: this is the FTS virtual table itself
                    continue
                # Some indices may have been auto-renamed; ALTER on a
                # table that no longer exists is a no-op error we
                # tolerate via IF EXISTS-style guard.
                conn.execute(f'ALTER TABLE "{step.src_table}" RENAME TO "{step.dst_table}"')

            # Phase 3: rebuild FTS virtual tables + triggers under the
            # destination namespace, then repopulate FTS from the
            # renamed base tables.
            _rebuild_fts_and_triggers(conn, plan.dst_namespace)
        elif plan.mode == "copy":
            # CREATE TABLE dst AS SELECT * FROM src — preserves rows
            # but loses indexes / triggers / FTS5 contentless table
            # specifics. The caller MUST instantiate a fresh
            # ``Memory(namespace=dst)`` afterwards so the
            # ``_init_schema`` recreates indexes + triggers + FTS
            # virtual tables. For FTS virtual tables we skip — the
            # new namespace's _init_schema will rebuild them and the
            # AFTER INSERT triggers will re-populate from the copied
            # base tables.
            for step in plan.steps:
                if step.is_fts_shadow:  # actually "is FTS virtual" — see plan_rename
                    continue
                conn.execute(f'CREATE TABLE "{step.dst_table}" AS SELECT * FROM "{step.src_table}"')
            # The copied {dst}_meta carries the source's fts_text_version,
            # which would make the destination's first _init_schema skip
            # the FTS rebuild and leave the copied namespace unsearchable.
            # Clear the marker so the rebuild runs against the copied rows.
            meta_table = f"{plan.dst_namespace}_meta"
            exists = conn.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (meta_table,)).fetchone()
            if exists:
                conn.execute(f'DELETE FROM "{meta_table}" WHERE key = ?', ("fts_text_version",))
        else:
            raise ValueError(f"unknown mode: {plan.mode!r}")

        conn.commit()
        committed = True
    finally:
        try:
            if not committed:
                conn.rollback()
        finally:
            conn.close()

    return len(plan.steps)


# ---------------------------------------------------------------------------
# Internal: FTS / trigger inventory + reconstruction
# ---------------------------------------------------------------------------


def _collect_fts_tables(conn: sqlite3.Connection, namespace: str) -> list[str]:
    """Return every FTS5 virtual table under ``namespace``.

    Return every FTS5 virtual table under ``namespace`` (excludes shadows
    — dropping the virtual table cascades to shadows automatically)."""
    escaped = namespace.replace("_", "\\_")
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "  AND name LIKE ? ESCAPE '\\' "
        "  AND sql LIKE 'CREATE VIRTUAL TABLE%' "
        "ORDER BY name",
        (escaped + "\\_%",),
    ).fetchall()
    return [r[0] for r in rows]


def _collect_triggers(conn: sqlite3.Connection, namespace: str) -> list[str]:
    """Return trigger names that begin with ``{namespace}_``."""
    escaped = namespace.replace("_", "\\_")
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='trigger' AND name LIKE ? ESCAPE '\\' ORDER BY name",
        (escaped + "\\_%",),
    ).fetchall()
    return [r[0] for r in rows]


# Map of base table → FTS5 virtual table spec used to reconstruct the
# index. Mirrors ``_init_schema`` in :mod:`octop_memory.storage.backends.sqlite`.
# Updating either side without the other will cause silent FTS drift, so
# CI's e2e test (M5.8 — deferred per D46-C, but worth adding back when
# we ship multi-backend) should round-trip a rename + search query.
_FTS_SPECS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    # (base_table_suffix, trigger_prefix, fts_table_suffix, (column1, ...)).
    # trigger_prefix MUST match _init_schema's trigger names ({ns}_memory_ai
    # etc.) — a different name here would survive the next _init_schema's
    # CREATE TRIGGER IF NOT EXISTS and double-insert into FTS.
    ("memory_nodes", "memory", "memory_fts", ("content", "topic")),
    ("messages", "messages", "messages_fts", ("content",)),
    ("raw_events", "raw_events", "raw_events_fts", ("content",)),
    ("candidates", "candidates", "candidates_fts", ("title", "assertion", "verbatim_quote")),
    ("atoms", "atoms", "atoms_fts", ("assertion", "verbatim_quote", "search_terms")),
)


def _rebuild_fts_and_triggers(conn: sqlite3.Connection, namespace: str) -> None:
    """Recreate FTS5 tables and sync triggers for ``namespace``.

    Recreate FTS5 tables + AFTER INSERT/UPDATE/DELETE triggers under
    ``namespace`` and repopulate the FTS index from the base table.

    Both the trigger bodies and the repopulation pass run every value
    through ``hm_cjk_seg`` so the rebuilt index keeps the per-character
    CJK segmentation (see :mod:`octop_memory.storage.backends.fts_text`).
    """
    register_fts_functions(conn)
    for base_suffix, trigger_prefix, fts_suffix, columns in _FTS_SPECS:
        base = f"{namespace}_{base_suffix}"
        fts = f"{namespace}_{fts_suffix}"

        # Skip if the base table doesn't exist (the suffix list covers
        # M0/M1 tables that may be absent in newer namespaces).
        existing = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
            (base,),
        ).fetchone()
        if not existing:
            continue

        col_list = ", ".join(columns)
        new_vals = ", ".join(f"hm_cjk_seg(new.{c})" for c in columns)
        old_vals = ", ".join(f"hm_cjk_seg(old.{c})" for c in columns)
        conn.execute(
            f'CREATE VIRTUAL TABLE "{fts}" USING fts5('
            f"{col_list}, content='{base}', content_rowid='rowid', tokenize='unicode61')"
        )

        # AFTER INSERT trigger
        conn.execute(
            f'CREATE TRIGGER "{namespace}_{trigger_prefix}_ai" AFTER INSERT ON "{base}" BEGIN '
            f'  INSERT INTO "{fts}"(rowid, {col_list}) VALUES (new.rowid, {new_vals}); '
            f"END"
        )

        # AFTER DELETE trigger uses the FTS5 'delete' sentinel column
        # whose name MUST equal the FTS table name — recreated under
        # the new namespace so it stays consistent.
        conn.execute(
            f'CREATE TRIGGER "{namespace}_{trigger_prefix}_ad" AFTER DELETE ON "{base}" BEGIN '
            f'  INSERT INTO "{fts}"({fts}, rowid, {col_list}) '
            f"  VALUES ('delete', old.rowid, {old_vals}); "
            f"END"
        )

        # AFTER UPDATE trigger only emitted for tables that need it.
        # Memory_nodes / candidates / atoms have UPDATE triggers in
        # _init_schema; raw_events / messages do not (immutable).
        if base_suffix not in ("raw_events", "messages"):
            conn.execute(
                f'CREATE TRIGGER "{namespace}_{trigger_prefix}_au" AFTER UPDATE ON "{base}" BEGIN '
                f'  INSERT INTO "{fts}"({fts}, rowid, {col_list}) '
                f"  VALUES ('delete', old.rowid, {old_vals}); "
                f'  INSERT INTO "{fts}"(rowid, {col_list}) '
                f"  VALUES (new.rowid, {new_vals}); "
                f"END"
            )

        # Repopulate FTS from the base table.
        col_select = ", ".join(f"hm_cjk_seg({c})" for c in columns)
        conn.execute(f'INSERT INTO "{fts}"(rowid, {col_list}) SELECT rowid, {col_select} FROM "{base}"')


__all__ = ["RenameMode", "RenamePlan", "TablePlan", "apply_rename", "plan_rename"]
