"""Data types for the memory system."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal

# ---------------------------------------------------------------------------
# Memory tree
# ---------------------------------------------------------------------------


@dataclass
class MemoryNode:
    """An organizational node in the memory tree.

    ``root`` and ``branch`` nodes own their directory labels in
    ``content``. A ``leaf`` does not own a second copy of fact text:
    ``atom_id`` references the canonical :class:`AtomCard`, and backends
    project ``AtomCard.assertion`` into ``content`` when reading the node.

    ``metadata`` is free-form organizational metadata. It is persisted
    but never indexed by FTS.
    """

    id: str
    parent_id: str | None
    level: Literal["root", "branch", "leaf"]
    content: str
    topic: str | None
    conversation_id: str | None
    created_at: datetime
    updated_at: datetime
    metadata: dict[str, Any] = field(default_factory=dict)
    atom_id: str | None = None


# ---------------------------------------------------------------------------
# L0 Raw events (M1)
# ---------------------------------------------------------------------------


RawEventType = Literal[
    "user_message",
    "assistant_message",
    "tool_call",
    "tool_result",
    "host_memory_write",
    "session_start",
    "session_end",
    "compaction",
    "manual",
]


@dataclass
class RawEvent:
    """A single L0 raw event captured from the host agent.

    L0 is the evidence source for the plugin: every promoted fact keeps
    links back to raw events so extraction and promotion remain auditable.
    ``AtomCard`` is the canonical current-fact record. RawEvent rows are
    immutable after insert; corrections happen by appending new events,
    never by mutating old ones.

    Fields:
    - ``id``: stable UUID generated by the plugin (not by the host).
    - ``host``: ``"openclaw"`` / ``"hermes"`` / ``"ace"`` / ``"manual"``.
    - ``session_id`` / ``thread_id`` / ``user``: optional host context;
      filled by the adapter when available. Hosts differ in which they
      have: Hermes only ever supplies ``session_id`` (``thread_id`` is
      always ``None``), OpenClaw supplies both as distinct values, and
      hosts with no session concept pass the thread id for both.
    - ``timestamp``: when the event happened (host-supplied if present,
      otherwise plugin local clock at capture time).
    - ``event_type``: the kind of event (see ``RawEventType``).
    - ``content``: the searchable text body (FTS-indexed).
    - ``payload``: arbitrary structured fields (role / tool_name /
      target_file / token_usage / ...). NOT indexed by FTS.
    """

    id: str
    host: str
    session_id: str | None
    thread_id: str | None
    user: str | None
    timestamp: datetime
    event_type: RawEventType
    content: str
    payload: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# L1 Candidates (M2)
# ---------------------------------------------------------------------------


CandidateType = Literal[
    "Fact",
    "Decision",
    "Task",
    "Preference",
    "ConflictCandidate",
]
CandidateStatus = Literal[
    "pending",
    "promoted",
    "rejected",
    "needs_review",
    "conflict",
    "extractor_failed",
]
EntityType = Literal[
    "User",
    "Person",
    "Project",
    "Decision",
    "Task",
    "Fact",
]
ConfidenceLevel = Literal["low", "medium", "high"]
ImportanceLevel = Literal["low", "medium", "high"]
RecommendedAction = Literal[
    "promote",
    "merge",
    "update",
    "reject",
    "conflict",
    "needs_review",
]
DecidedBy = Literal["auto", "user", "rule", "portable"]


@dataclass
class Candidate:
    """L1 Candidate — an LLM-extracted fact awaiting promotion to atom.

    Candidates are extracted from raw events at ``session_end`` (light cadence)
    or daily (heavy cadence). They are mutable until ``status`` becomes
    terminal (``promoted`` / ``rejected``); ``needs_review`` and ``conflict``
    sit in a queue waiting for user decision.

    Anti-dilution rule (D25 / design §8.6): when ``importance == "high"``,
    ``assertion`` must equal ``verbatim_quote`` — extractor is forbidden to
    paraphrase. ``verbatim_quote`` is the exact user phrase (≤200 chars) and
    ``quote_event_id`` points to the raw event it came from. Negation /
    qualifier words ("不"/"先"/"暂"/"not"/"won't") must be preserved in
    ``assertion`` even for low importance.

    ``id`` and ``target_entity_id`` are assigned by the worker, NOT by the
    LLM (deterministic ids, no hallucinated entity refs).
    """

    id: str
    raw_event_ids: list[str]
    candidate_type: CandidateType
    status: CandidateStatus
    title: str
    assertion: str
    verbatim_quote: str
    quote_event_id: str
    subject_name: str
    subject_entity_type: EntityType
    target_entity_id: str | None
    confidence: ConfidenceLevel
    importance: ImportanceLevel
    recommended_action: RecommendedAction
    promotion_reason: str
    extractor_version: str
    created_at: datetime
    decided_at: datetime | None = None
    decided_by: DecidedBy | None = None
    session_id: str | None = None
    payload: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# L2 Atoms (M2)
# ---------------------------------------------------------------------------


@dataclass
class AtomCard:
    """L2 AtomCard — a structured fact promoted from a candidate.

    Atoms are the primary recall layer: the recall path returns
    atom snippets first and falls back to raw events only when atom count is
    insufficient. Atoms link upward to ``entity_id`` (L3 EntityPage) and
    backward to ``candidate_id`` and ``raw_event_ids`` (L0 source refs) so
    that recall results can always cite original quotes.

    Atoms are *append-only with deprecation*: when a fact is updated, a new
    atom is created and the old one's ``superseded_by`` points to the new
    id (with ``deprecated_at`` set). This preserves audit history. Recall
    filters out atoms with ``deprecated_at IS NOT NULL`` by default.
    """

    id: str
    entity_id: str
    candidate_id: str
    raw_event_ids: list[str]
    assertion: str
    verbatim_quote: str
    quote_event_id: str
    search_terms: list[str]
    occurred_at: datetime
    confidence: ConfidenceLevel
    importance: ImportanceLevel
    created_at: datetime
    superseded_by: str | None = None
    deprecated_at: datetime | None = None


# ---------------------------------------------------------------------------
# L3 Entities — narrow anchors; long summaries live in EntityPage
# ---------------------------------------------------------------------------


@dataclass
class Entity:
    """L3 Entity — narrow anchor for atoms and alias resolution.

    The row stores only bookkeeping fields needed for atom association
    and string normalization. Long-form fields such as
    ``summary_markdown`` and ``summary_version`` intentionally live in
    the separate :class:`EntityPage` record.

    ``aliases`` holds the original-case display forms. Alias *lookup* is
    keyed off the separate ``Alias`` table, whose ``alias`` column is
    normalized for matching — the two are not copies of each other.
    """

    id: str
    entity_type: EntityType
    canonical_name: str
    aliases: list[str]
    atom_count: int
    created_at: datetime
    last_promoted_at: datetime | None = None


@dataclass
class Alias:
    """Alias-table row mapping a normalized string to an entity.

    Used by the promotion worker's check 3 (string normalization). The
    ``alias`` field is lowercased + whitespace-collapsed for matching.
    ``created_by`` records whether the alias was generated by ``rule``
    (string match), ``auto`` (LLM disambiguation), or ``user`` (manual
    review).
    """

    alias: str
    entity_id: str
    entity_type: EntityType
    created_by: DecidedBy
    created_at: datetime


# ---------------------------------------------------------------------------
# L3 Entity Page (M3 — full summary; built on top of the M2 minimal Entity)
# ---------------------------------------------------------------------------


@dataclass
class EntityPage:
    """L3 Entity Page — the long-form summary attached to an :class:`Entity`.

    A separate ``entity_page`` table (one row per entity_id) keeps the
    minimal :class:`Entity` row narrow / hot while the page payload
    (which can be large markdown) lives in its own table that recall
    doesn't always need to load.

    Fields and decisions:

    - ``summary_markdown``: LLM-generated markdown body. May contain a
      ``## My Notes`` heading section that the user has hand-edited; the
      regenerator MUST preserve that section verbatim (D34-A).
    - ``headline``: pre-computed ≤30-char hot summary (D32-A; stored as
      a separate column rather than parsed from markdown — the recall
      path must NOT do markdown parsing).
    - ``topics``: short list of topic keywords; reserved for the query
      router. Empty list is fine.
    - ``dirty``: D33-B — set ``True`` whenever a candidate gets promoted
      against this entity; the async cron worker
      (``memory page regen --dirty``) clears it on successful regen.
      New rows default to ``True`` so a brand-new entity is always
      regenerated at least once.
    - ``regen_attempt_count``: increments on each LLM regen failure.
      Stays ``dirty=True`` so the next cron tick retries (D35-A: keep
      old summary on failure rather than blank it out). Reset to 0 on
      success.
    - ``last_regen_at``: timestamp of the last successful regeneration
      (None until the first one).
    - ``last_user_edit_at``: timestamp of the last user-applied edit to
      ``summary_markdown`` (via ``memory entity edit``). The regenerator
      uses this to detect concurrent user changes.
    - ``summary_version``: monotonically increasing integer — bumped on
      every successful regen and on every user edit. Useful for D35
      rollback debugging and for clients that want to detect "page
      changed since I last looked".

    Page rows are upserted by ``entity_id``; they are NOT append-only
    (in contrast to atoms). The journal captures every regen success,
    failure, and user edit so the history is still reconstructible.
    """

    id: str
    entity_id: str
    summary_markdown: str
    headline: str
    topics: list[str]
    dirty: bool
    regen_attempt_count: int
    summary_version: int
    created_at: datetime
    updated_at: datetime
    last_regen_at: datetime | None = None
    last_user_edit_at: datetime | None = None


# ---------------------------------------------------------------------------
# L2.5 Episodes — daily emotional / situational diary entries (M5)
# ---------------------------------------------------------------------------

EpisodeEmotion = Literal[
    "neutral",
    "happy",
    "sad",
    "angry",
    "anxious",
    "excited",
    "frustrated",
    "grateful",
    "tired",
    "reflective",
]


@dataclass
class Episode:
    """L2.5 Episode — a user-centric situational/emotional diary entry.

    Episodes are the "diary" layer that lives alongside (NOT replacing)
    AtomCards. Where atoms capture stable, queryable facts ("wife's name
    is Xiaoli"), episodes capture **what happened to the user** and **how
    they felt** on a given day ("had a fight with my wife because she said
    I never help around the house"). Without this layer
    the agent forgets day-to-day life events because the candidate
    extractor explicitly filters them out as "transient emotion / casual
    chat" (see extractor prompt).

    Episodes are extracted in parallel with candidates during the same
    ``service.extract()`` call but use a dedicated prompt that ONLY
    looks for first-person events / feelings. They never enter the atom
    pipeline and never auto-promote to entities — they are an
    independent recall source.

    Field semantics:
    - ``occurred_at``: when the event the user described happened (best
      effort: defaults to the source raw event timestamp).
    - ``summary``: ≤120-char neutral summary written in 3rd-person from
      the user's POV ("user had a fight with their wife"). Used for
      recall snippets.
    - ``verbatim_quote``: ≤200-char direct quote from the user's raw
      text — preserves the original phrasing and emotional tone.
    - ``emotion``: one of :data:`EpisodeEmotion`. ``neutral`` is the
      catch-all when no strong emotional signal is present.
    - ``intensity``: 1-5; how strongly the emotion is expressed.
      1 = mild / passing, 3 = clearly felt, 5 = overwhelming.
    - ``people``: free-form names mentioned ("wife", "boss", "Xiao Li").
      NOT linked to entity IDs — episode names are often pronouns / titles
      that don't normalize cleanly. The recall layer treats these as
      plain search tokens.
    - ``topics``: short tags like "family" / "work" / "health" / "project".
    - ``raw_event_ids``: source events for traceability.
    - ``digest_ids``: weekly/monthly digest rows that have already
      consumed this episode (for incremental aggregation). Empty until
      the first digest covers it.
    """

    id: str
    raw_event_ids: list[str]
    occurred_at: datetime
    summary: str
    verbatim_quote: str
    quote_event_id: str
    emotion: EpisodeEmotion
    intensity: int
    people: list[str]
    topics: list[str]
    extractor_version: str
    created_at: datetime
    session_id: str | None = None
    digest_ids: list[str] = field(default_factory=list)


DigestPeriod = Literal["daily", "weekly", "monthly"]


@dataclass
class DigestRecord:
    """A generated daily/weekly/monthly digest of episodes.

    The digest is "a diary/weekly report the agent writes for you" — a
    compact, human-readable markdown summary of one day's (or week /
    month's) episodes. Stored as both:

    - the SQLite row (this dataclass) — for indexed lookup and recall
    - an exported markdown file under ``<workspace>/journals/<key>.md``
      — for the user to read and edit

    Daily is the primary aggregator (matches the granularity of emotional
    memory, i.e. "how was today"); weekly/monthly are optional roll-ups
    that summarize the day-level
    digests rather than the raw episodes.

    Fields:
    - ``period_key``: ISO date ("2026-06-26"), ISO week ("2026-W26"),
      or month ("2026-06"). Unique per period_kind.
    - ``period_start`` / ``period_end``: half-open ``[start, end)``
      window expressed in the user's local timezone (UTC offset baked
      in at write time).
    - ``markdown``: full digest body, ready to write to disk.
    - ``episode_ids``: which episodes were included (for
      reproducibility / incremental regen).
    - ``llm_version``: stamp of the digest prompt version used.
    """

    id: str
    period_kind: DigestPeriod
    period_key: str
    period_start: datetime
    period_end: datetime
    markdown: str
    episode_ids: list[str]
    llm_version: str
    created_at: datetime
    updated_at: datetime


# ---------------------------------------------------------------------------
# L4 Journal (M2 + M3 page actions)
# ---------------------------------------------------------------------------


JournalAction = Literal[
    "create",
    "extract_run",
    "promote",
    "update",
    "merge",
    "conflict",
    "deprecate",
    "delete",
    "user_edit",
    "reject",
    "page_regen",
    "page_regen_failed",
    "page_user_edit",
    "gc_rejected_candidate",
    "gc_deprecated_atom",
    "gc_orphan_raw_event",
    "consolidate",
    "entity_merge",
    "migration_in",
]


@dataclass
class JournalEntry:
    """L4 Journal entry — append-only audit log of memory mutations.

    The journal is *not* used for recall (it's a debugging / replay tool).
    Every mutation to candidates, atoms, or entities — whether by ``auto``
    promotion, ``user`` review, or ``rule`` fallback — appends one row.
    ``before`` / ``after`` capture the relevant fields as JSON for
    diffing.

    Pipeline / heartbeat actions (``extract_run``, ``gc_*``, ``page_regen*``,
    ``consolidate``) expire after a short retention window (ADR-028).
    New extract passes write ``last_extract_run`` in meta instead of
    appending ``extract_run`` rows; leftover historical rows are GC'd.
    """

    id: str
    timestamp: datetime
    action: JournalAction
    actor: DecidedBy
    target_entity_id: str | None = None
    target_atom_id: str | None = None
    target_candidate_id: str | None = None
    before: dict[str, Any] | None = None
    after: dict[str, Any] | None = None
    note: str = ""


@dataclass
class ThreadSummary:
    """Summary of a checkpointed thread."""

    thread_id: str
    checkpoint_id: str
    created_at: datetime | None
    updated_at: datetime | None


@dataclass
class ActiveEntity:
    """One entry in the thread-active-entity LRU stack (D41a + D41b).

    Each row records that ``entity_id`` was *active* in ``thread_id`` at
    ``last_seen_at`` because of ``source`` (recall hit vs query mention).
    The recall router uses these rows to resolve co-references like
    "那个项目" by reading the most-recently-seen entity for the current
    thread.

    The table is keyed on ``(thread_id, entity_id)`` — re-seeing the same
    entity refreshes ``last_seen_at`` rather than appending a duplicate.
    """

    thread_id: str
    entity_id: str
    last_seen_at: datetime
    # Why this entity entered the stack — for debugging only:
    # - "recall_hit": query matched an atom that belongs to this entity (D41a-A)
    # - "query_mention": entity name literal appeared in the query text (D41a-C)
    # - "manual": tooling / tests injected it explicitly
    source: Literal["recall_hit", "query_mention", "manual"] = "recall_hit"


@dataclass
class ThreadState:
    """Full state of a checkpointed thread."""

    thread_id: str
    checkpoint_id: str
    channel_values: dict[str, Any]
    metadata: dict[str, Any]
    created_at: datetime | None


__all__ = [
    "Alias",
    "AtomCard",
    "Candidate",
    "CandidateStatus",
    "CandidateType",
    "ConfidenceLevel",
    "DecidedBy",
    "DigestPeriod",
    "DigestRecord",
    "Entity",
    "EntityPage",
    "EntityType",
    "Episode",
    "EpisodeEmotion",
    "ImportanceLevel",
    "JournalAction",
    "JournalEntry",
    "MemoryNode",
    "RawEvent",
    "RawEventType",
    "RecommendedAction",
    "ThreadState",
    "ThreadSummary",
]
