"""Lifecycle management — GC, consolidation, vacuum, idle maintenance."""

from octop_memory.pipeline.lifecycle.consolidate import (
    DEFAULT_JACCARD_PREFILTER,
    DEFAULT_MAX_ENTITIES,
    DEFAULT_MAX_LLM_CALLS,
    DEFAULT_MIN_ATOMS,
    ConsolidationStats,
    DuplicateCluster,
    run_consolidation,
)
from octop_memory.pipeline.lifecycle.gc import (
    DEFAULT_DEPRECATED_ATOM_DAYS,
    DEFAULT_JOURNAL_PIPELINE_DAYS,
    DEFAULT_MAX_ROWS_PER_PASS,
    DEFAULT_ORPHAN_RAW_DAYS,
    DEFAULT_REJECTED_CANDIDATE_DAYS,
    PIPELINE_JOURNAL_ACTIONS,
    GcStats,
    run_gc,
)
from octop_memory.pipeline.lifecycle.maintenance import (
    BOOTSTRAP_WINDOWS,
    DEFAULT_BOOTSTRAP_DISK_MARGIN_BYTES,
    DEFAULT_BOOTSTRAP_HARD_BYTES,
    DEFAULT_BOOTSTRAP_SOFT_BYTES,
    DEFAULT_WAL_TRUNCATE_BYTES,
    BootstrapStats,
    IdleMaintenanceStats,
    WalTruncateStats,
    maybe_bootstrap_incremental,
    maybe_truncate_wal,
    run_idle_maintenance,
)
from octop_memory.pipeline.lifecycle.vacuum import (
    DEFAULT_INCREMENTAL_VACUUM_PAGES,
    CompactStats,
    TableVacuumResult,
    VacuumStats,
    compact_vacuum,
    nudge_vacuum,
    tune_checkpoint_autovacuum,
)

__all__ = [
    "BOOTSTRAP_WINDOWS",
    "DEFAULT_BOOTSTRAP_DISK_MARGIN_BYTES",
    "DEFAULT_BOOTSTRAP_HARD_BYTES",
    "DEFAULT_BOOTSTRAP_SOFT_BYTES",
    "DEFAULT_DEPRECATED_ATOM_DAYS",
    "DEFAULT_INCREMENTAL_VACUUM_PAGES",
    "DEFAULT_JACCARD_PREFILTER",
    "DEFAULT_JOURNAL_PIPELINE_DAYS",
    "DEFAULT_MAX_ENTITIES",
    "DEFAULT_MAX_LLM_CALLS",
    "DEFAULT_MAX_ROWS_PER_PASS",
    "DEFAULT_MIN_ATOMS",
    "DEFAULT_ORPHAN_RAW_DAYS",
    "DEFAULT_REJECTED_CANDIDATE_DAYS",
    "DEFAULT_WAL_TRUNCATE_BYTES",
    "PIPELINE_JOURNAL_ACTIONS",
    "BootstrapStats",
    "CompactStats",
    "ConsolidationStats",
    "DuplicateCluster",
    "GcStats",
    "IdleMaintenanceStats",
    "TableVacuumResult",
    "VacuumStats",
    "WalTruncateStats",
    "compact_vacuum",
    "maybe_bootstrap_incremental",
    "maybe_truncate_wal",
    "nudge_vacuum",
    "run_consolidation",
    "run_gc",
    "run_idle_maintenance",
    "tune_checkpoint_autovacuum",
]
